services:
  db:
    image: postgres:16-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      default:
        ipv4_address: 172.28.5.2
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.dev.sql:/docker-entrypoint-initdb.d/01-create-database.sql
      - ./init-grant-permissions.sh:/docker-entrypoint-initdb.d/02-grant-permissions.sh

  cache:
    image: "redis:7.0-alpine"
    restart: on-failure
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Da3ZqphucUo4zw9b", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    command: redis-server --save 10 1 --loglevel warning --requirepass Da3ZqphucUo4zw9b
    volumes:
      - redis_data:/data
    networks:
      default:
        ipv4_address: 172.28.5.4

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: on-failure
    ports:
      - "8081:8001"
    environment:
      - RITRUSTEDORIGINS=http://localhost:8081,http://127.0.0.1:8081,http://0.0.0.0:8081
    volumes:
      - redisinsight:/db
    networks:
      default:
        ipv4_address: 172.28.5.5
    depends_on:
      cache:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:8001 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:latest
    restart: on-failure
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage
      - ./pgadmin_default_servers.json:/pgadmin4/servers.json
      - ./pgadmin_passfile:/pgadmin4/pgpassfile
    networks:
      default:
        ipv4_address: 172.28.5.6

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: studoto-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=172.28.5.2
      - DB_PORT=5432
      - DB_USER=studoto
      - DB_PASSWORD=studoto
      - DB_NAME=studoto
      - DB_SSLMODE=disable
      - REDIS_HOST=172.28.5.4
      - REDIS_PORT=6379
      - REDIS_PASSWORD=Da3ZqphucUo4zw9b
      - REDIS_DB=0
      - PORT=8080
    networks:
      default:
        ipv4_address: 172.28.5.7
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
    links:
      - db

volumes:
  db:
  pgadmin:
  redisinsight:
  redis_data:

networks:
  default:
    name: studoto
    external: true
